### ISSUE TITLE
Logging actions on dhcp client local stop

### ISSUE THREAD

**Issue by Egorkat** [loiklo/mikrotik#1]
Hello Alexander!
Please advise where to add logging/notification actions when dhcp lease is stopped locally?
F.e. if Main ISP router is powered off or ethernet cable from it is disconnected. mikrotik logs:
dhcp-client on ether1-MainISP lost IP address aa.bb.cc.dd - lease stopped locally
route removed by mtik_admin
route removed by mtik_admin
route removed by mtik_admin
route removed by mtik_admin
route removed by mtik_admin

And nothing is logged, related to switchover. Seems it happens before main if block, where ping checks are done.

**Comment by loiklo** [comment]
Hello,

I did this script to mainly handle logical link failure, when the main ISP router is still here but its uplink is down. Basically, the failover when the cable is physically unplugged or the ISP router is powered off (which is basically the same as disconnected the cable from the Mkt side) is instant since it is managed by the default route distance, and I didn't really handle that case.

Anyway, to test at home, I just tried to unplug the network cable on my router and here are the logs.
I'm running the long-term branch, currently version 6.47.10 on a rb4011 with the following settings:
```
:local mainInterface "br-wan";
:local backupInterface "ether2";
```


```
08:12:14 interface,info ether1 link down 
08:12:40 system,info dhcp client changed by alex 
08:12:40 script,info Detected main link failure, switching to backup link 
08:12:40 dhcp,info dhcp-client on br-wan lost IP address 12.34.56.78 - lease stopped locally 
08:13:31 system,info route removed by alex 
08:13:31 system,info route removed by alex 
08:13:31 system,info route removed by alex 
08:13:31 system,info route removed by alex 
08:13:31 system,info route removed by alex 
08:13:32 system,info dhcp client changed by alex 
08:13:32 script,info Main link back online, switching back to main link 
08:13:43 interface,info ether1 link up (speed 1G, full duplex) 
08:13:44 dhcp,info dhcp-client on br-wan got IP address 12.34.56.78 
08:14:30 system,info route added by alex 
08:14:31 system,info route added by alex 
08:14:31 system,info route added by alex 
08:14:31 system,info route added by alex 
08:14:31 system,info route added by alex 
```

Maybe what you want is to:
- trigger an action when a specific log is written: https://wiki.mikrotik.com/wiki/Manual:Scripting-examples#Detect_new_log_entry
or
- trigger an action when the dhcp-lease is added/removed: https://wiki.mikrotik.com/wiki/Manual:IP/DHCP_Client#Lease_script_example

**Comment by Egorkat** [comment]
for me powering down ISP device or pulling out ethernet cable from it looks like on the attached screenshot, no info messages from the script, only route actions
![log](https://user-images.githubusercontent.com/10372472/134885184-f82982bf-343c-4994-b83d-74e0f0073b3b.png)

**Comment by loiklo** [comment]
I don't really understand what happens.
- Are your 2 ISPs provide IP in DHCP? (this script rely on distance set by the dhcp-client)
- What are your User variables?

If the routes are added/removed but there is nothing in logs, I suggest to print all variables in code block starting from line 139. So you should know why this part of the code is not executed.

To explain the code blocks if you want to troubleshoot the problem:
L77: Clean a previous run if you change the testHosts
L91: Force the route distance of backup ISP
L105: Add/Remove routes on the main ISP to allow the testHosts to be reached from the backup ISP as soon as the main interface doesn't have a dhcp lease. 
L123: Ping loop to test Internet connectivity
L139: Play with the route distance through the dhcp-client service to send traffic through main or backup ISP and enforce a dhcp-release if Internet is down though the main ISP

**Comment by Egorkat** [comment]
Yes, I have 2 ISPs with DHCP. Will try to troubleshoot as you suggested, thank you!

**Comment by Egorkat** [comment]
Hi Alexander, managed today to test failover being near the router, as remotely is hard to pull out the cable to start the test :-)
I've added some lines to your script as I need to be notified via Telegram on line state changes and per your advise I've added echoing all variables in script. Here is the main part, sorry for the broken formatting - github parser does that:
` 
    # Add/remove more-specific routes to testHosts depending of mainInterface dhcp status and lease
    # If DHCP status is bound:
    #   Remove testHosts routes from previous lease (if any)
    #   Add testHosts /32 routes if not already exist
    # Else (DHCP status not bound):
    #   Remove all testHosts /32 routes
    :local mainGatewayDhcpInfo [:pick [/ip dhcp-client print as-value detail where interface=$mainInterface] 0];
    :local mainGatewayDhcpStatus ($mainGatewayDhcpInfo->"status");
    :local mainGatewayDhcpGatewayIp ($mainGatewayDhcpInfo->"gateway");
    :local mainGatewayDhcpIp ($mainGatewayDhcpInfo->"address");
    :local mainIP [:pick $mainGatewayDhcpIp 0 [:find $mainGatewayDhcpIp "/"]];  #<-- added
    :local backupGatewayDhcpInfo [:pick [/ip dhcp-client print as-value detail where interface=$backupInterface] 0];
    :local backupGatewayDhcpIp ($backupGatewayDhcpInfo->"address");
    :local backIP [:pick $backGatewayDhcpIp 0 [:find $backGatewayDhcpIp "/"]];  #<-- added
    :if ($mainGatewayDhcpStatus = "bound") do={
      :foreach testHost in=$testHosts do={
        :local testHostIp [:tostr ("$testHost"."/32")]; # Generate x.x.x.x/32 str from x.x.x.x
        # Remove route from previous lease (if any)
        /ip route remove [/ip route find where dst-address=$testHostIp and gateway!=[:tostr $mainGatewayDhcpGatewayIp]];
        # Add route if not already exists
        :if ([:len [/ip route find dst-address=$testHostIp]] = 0) do={
        :log info "Adding routes on line 103";  #<-- added echo
          /ip route add dst-address=$testHostIp gateway=[:tostr $mainGatewayDhcpGatewayIp] comment=$routeComment;
        }
      }
    } else={
      # Remove all testHosts /32 routes
      :foreach testHost in=$testHosts do={
        :local testHostIp [:tostr ("$testHost"."/32")];
        :log info "Removing routes on line 109"; # <-- added echo
        /ip route remove [/ip route find where dst-address=[:tostr $testHostIp]];
      }
    }
  
    # Ping loop, can exit earlier if the Success rate is reached
    :local pingSuccessCount 0;
    :local pingCount 1;
    :local pingRateSuccess 0;
    :while (($pingCount <= $pingPerHost) and ($pingRateSuccess < $pingRateSuccessExpected)) do={
      :foreach tHost in=$testHosts do={
        :if ([/ping address=$tHost count=1]=1) do={
          :set pingSuccessCount ($pingSuccessCount + 1);
          :delay [:totime $pingSuccessDelay];
        }
      }
      :set pingCount ($pingCount + 1);
      :set pingRateSuccess ($pingSuccessCount * 100 / ([:len $testHosts] * $pingPerHost));
    }
  
  :log info $pingRateSuccess; # <-- added echo
  :log info $pingRateSuccessExpected; # <-- added echo
    
    :if ($pingRateSuccess < $pingRateSuccessExpected) do={
      # Demote mainInterface
      :if ($currentMainRouteDistance != $mainDemoteRouteDistance) do={
        /ip dhcp-client set [/ip dhcp-client find where interface=$mainInterface] default-route-distance=$mainDemoteRouteDistance;
        :log info "Detected main link failure, switching to backup link";
        #>>> ADD HERE ACTIONS TO DO ON MAIN LINK FAILURE (email, http call, logging, ...)
        :local messageText "Main ISP is down, switching to 4G on $backIP"; #<-- added
        /tool fetch url="https://api.telegram.org/$botID/sendmessage\?chat_id=$chatId&text=$messageText" keep-result=no; # <-- added
      }
      # Release DHCP lease if bound to:
      # - allow the testHosts to be reached through the backupInterface
      # - force a DHCP renew in case of mainInterface subnet has changed on the provider side but our lease is not expired yet
      :if ($mainGatewayDhcpStatus = "bound") do={
        /ip dhcp-client release [/ip dhcp-client find interface=$mainInterface];
      }
    } else={
      # Promote mainInterface
      :if ($currentMainRouteDistance != $mainPromoteRouteDistance) do={
        /ip dhcp-client set [/ip dhcp-client find where interface=$mainInterface] default-route-distance=$mainPromoteRouteDistance;
        :log info "Main link back online, switching back to main link";
        #>>> ADD HERE ACTIONS TO DO ON MAIN LINK BACK ONLINE (email, http call, logging, ...)
        :local messageText "Main ISP is online on $mainIP"; # <-- added
        /tool fetch url="https://api.telegram.org/$botID/sendmessage\?chat_id=$chatId&text=$messageText" keep-result=no; # <-- added
      }
    }
  }
`

Under normal operation, script is executed each 30 seconds and logs only: 50, 5. These are pingRateSuccess and pingRateSuccessExpected. To speed up switchover, I've added script to dchp client events, so it is called when state is changed.
When main ISP cable is disconnected router logs the following:
22:27:01,10.11.100.1,"interface,info ether1-Starnet link down"
22:27:01,10.11.100.1,"dhcp,info dhcp-client on ether1-Starnet lost IP address **.**.**.** - lease stopped locally"
22:27:01,10.11.100.1,"script,info Removing routes on line 109"
22:27:01,10.11.100.1,"system,info route removed by gvp_admin"
22:27:01,10.11.100.1,"script,info Removing routes on line 109"
22:27:01,10.11.100.1,"system,info route removed by gvp_admin"
22:27:01,10.11.100.1,"script,info Removing routes on line 109"
22:27:01,10.11.100.1,"system,info route removed by gvp_admin"
22:27:01,10.11.100.1,"script,info Removing routes on line 109"
22:27:01,10.11.100.1,"script,info Removing routes on line 109"
22:27:01,10.11.100.1,"system,info route removed by gvp_admin"
22:27:01,10.11.100.1,"system,info route removed by gvp_admin"
22:27:02,10.11.100.1,"system,info route removed by gvp_admin"
22:27:02,10.11.100.1,"script,info 50"
22:27:02,10.11.100.1,"script,info 5"

Note the pingRateSuccess value is same 50, means script doesn't enter below line 139.
When I plug the cable back I see:
22:27:30,10.11.100.1,"interface,info ether1-Starnet link up (speed 1G, full duplex)"
22:27:31,10.11.100.1,"dhcp,info dhcp-client on ether1-Starnet got IP address **.**.**.**"
22:27:31,10.11.100.1,"script,info Adding routes on line 103"
22:27:31,10.11.100.1,"system,info route added by gvp_admin"
22:27:31,10.11.100.1,"script,info Adding routes on line 103"
22:27:31,10.11.100.1,"system,info route added by gvp_admin"
22:27:31,10.11.100.1,"script,info Adding routes on line 103"
22:27:31,10.11.100.1,"system,info route added by gvp_admin"
22:27:31,10.11.100.1,"script,info Adding routes on line 103"
22:27:31,10.11.100.1,"system,info route added by gvp_admin"
22:27:31,10.11.100.1,"script,info Adding routes on line 103"
22:27:31,10.11.100.1,"system,info route added by gvp_admin"
22:27:32,10.11.100.1,"script,info 50"
22:27:32,10.11.100.1,"script,info 5"

**Comment by loiklo** [comment]
Sorry, I completely forgot this gitlab issue. I'll still answer for anyone that could read the issue.
For me, the behavior you have is normal. This failover script handle **logical** link failure, when the cable is still plugged and ethernet protocol is up, but there is something broken on the ISP network and you have no/limited IP connectivity.

When you unplug physically the cable, the switchover is done instantaneously since the default route with the low weight is removed from the routing table by the router itself. So the default route become the backup link and the ping commands are still fine. You see the routes are removed in logs because the script ensure the dhcp lease is _bound_. This allow to reach the TestHosts IP through the backup link (/32 routes would prevent it)
